[package]
name = "RustAndMongoDB"
version = "0.1.0"
authors = ["renosyah <syahputrareno975@gmail.com>"]

[dependencies]
bson = "0.10.0"
mongodb = "0.3.7"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"